#!/bin/bash

[enter degree]

   

while [ $degree -gr 0 ] && [ "$degree" != "q" ]
    do 
       [bloc if]

    $i=$i++
    $sumDegree+=$degree
done

if [ $degree -lt 0 ] || [ "$degree" = "q" ]
        then   
            $moyenne =  $sumDegree/$i 
            echo = "La moyenne est $moyenne"
fi

